"""create contributors missions and agent audits

Revision ID: 7d09fba1cf79
Revises: 9a878c970899
Create Date: 2026-10-04 00:22:38.949246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d09fba1cf79'
down_revision: Union[str, Sequence[str], None] = '9a878c970899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('account_level', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributors_account_level'), 'contributors', ['account_level'], unique=False)
    op.create_index(op.f('ix_contributors_contributor_id'), 'contributors', ['contributor_id'], unique=True)
    op.create_index(op.f('ix_contributors_display_name'), 'contributors', ['display_name'], unique=True)
    op.create_index(op.f('ix_contributors_email'), 'contributors', ['email'], unique=True)
    op.create_index(op.f('ix_contributors_id'), 'contributors', ['id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('research_need', sa.Text(), nullable=False),
    sa.Column('research_need_source', sa.String(length=64), nullable=False),
    sa.Column('research_need_reference', sa.String(length=100), nullable=True),
    sa.Column('signal_case_id', sa.UUID(), nullable=True),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('target_latitude', sa.Float(), nullable=True),
    sa.Column('target_longitude', sa.Float(), nullable=True),
    sa.Column('required_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('collected_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('missing_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validation_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('next_action', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signal_case_id'], ['reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_contributor_id'), 'missions', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_missions_created_at'), 'missions', ['created_at'], unique=False)
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_index(op.f('ix_missions_mission_type'), 'missions', ['mission_type'], unique=False)
    op.create_index(op.f('ix_missions_research_need_source'), 'missions', ['research_need_source'], unique=False)
    op.create_index(op.f('ix_missions_signal_case_id'), 'missions', ['signal_case_id'], unique=False)
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_table('agent_action_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('tool_used', sa.String(length=64), nullable=False),
    sa.Column('input_reference', sa.String(length=255), nullable=True),
    sa.Column('output_reference', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_action_audits_action_type'), 'agent_action_audits', ['action_type'], unique=False)
    op.create_index(op.f('ix_agent_action_audits_created_at'), 'agent_action_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_action_audits_id'), 'agent_action_audits', ['id'], unique=False)
    op.create_index(op.f('ix_agent_action_audits_mission_id'), 'agent_action_audits', ['mission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_action_audits_mission_id'), table_name='agent_action_audits')
    op.drop_index(op.f('ix_agent_action_audits_id'), table_name='agent_action_audits')
    op.drop_index(op.f('ix_agent_action_audits_created_at'), table_name='agent_action_audits')
    op.drop_index(op.f('ix_agent_action_audits_action_type'), table_name='agent_action_audits')
    op.drop_table('agent_action_audits')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_index(op.f('ix_missions_signal_case_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_research_need_source'), table_name='missions')
    op.drop_index(op.f('ix_missions_mission_type'), table_name='missions')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_created_at'), table_name='missions')
    op.drop_index(op.f('ix_missions_contributor_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_contributors_id'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_email'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_display_name'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_contributor_id'), table_name='contributors')
    op.drop_index(op.f('ix_contributors_account_level'), table_name='contributors')
    op.drop_table('contributors')
    # ### end Alembic commands ###
