"""create human_reviews and evidence_lineage_events tables

Revision ID: 9a878c970899
Revises: be59c5463341
Create Date: 2026-10-03 00:56:40.831484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a878c970899'
down_revision: Union[str, Sequence[str], None] = 'be59c5463341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_lineage_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_case_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('source_service', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('structured_payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_case_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_lineage_events_created_at'), 'evidence_lineage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_lineage_events_event_type'), 'evidence_lineage_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_evidence_lineage_events_id'), 'evidence_lineage_events', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_lineage_events_signal_case_id'), 'evidence_lineage_events', ['signal_case_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('signal_case_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('linked_case_id', sa.UUID(), nullable=True),
    sa.Column('evidence_state_before', sa.String(length=50), nullable=False),
    sa.Column('evidence_state_after', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_case_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_id'), 'human_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_human_reviews_report_id'), 'human_reviews', ['report_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_signal_case_id'), 'human_reviews', ['signal_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_reviews_signal_case_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_report_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_evidence_lineage_events_signal_case_id'), table_name='evidence_lineage_events')
    op.drop_index(op.f('ix_evidence_lineage_events_id'), table_name='evidence_lineage_events')
    op.drop_index(op.f('ix_evidence_lineage_events_event_type'), table_name='evidence_lineage_events')
    op.drop_index(op.f('ix_evidence_lineage_events_created_at'), table_name='evidence_lineage_events')
    op.drop_table('evidence_lineage_events')
    # ### end Alembic commands ###
