"""create report_media table

Revision ID: be59c5463341
Revises: 044b4008265c
Create Date: 2026-09-30 20:01:04.190089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be59c5463341'
down_revision: Union[str, Sequence[str], None] = '044b4008265c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_media_id'), 'report_media', ['id'], unique=False)
    op.create_index(op.f('ix_report_media_report_id'), 'report_media', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_media_sha256'), 'report_media', ['sha256'], unique=False)
    op.create_index(op.f('ix_report_media_storage_key'), 'report_media', ['storage_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_media_storage_key'), table_name='report_media')
    op.drop_index(op.f('ix_report_media_sha256'), table_name='report_media')
    op.drop_index(op.f('ix_report_media_report_id'), table_name='report_media')
    op.drop_index(op.f('ix_report_media_id'), table_name='report_media')
    op.drop_table('report_media')
    # ### end Alembic commands ###
