"""create_mission_needs_table_and_add_mission_need_id_to_missions

Revision ID: fb97a1f0ec5b
Revises: 7d09fba1cf79
Create Date: 2026-10-04 02:24:33.927861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb97a1f0ec5b'
down_revision: Union[str, Sequence[str], None] = '7d09fba1cf79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_needs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_gap_dimension', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_by_researcher', sa.String(length=100), nullable=False),
    sa.Column('source_case_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('target_stream_segments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('required_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_needs_created_at'), 'mission_needs', ['created_at'], unique=False)
    op.create_index(op.f('ix_mission_needs_evidence_gap_dimension'), 'mission_needs', ['evidence_gap_dimension'], unique=False)
    op.create_index(op.f('ix_mission_needs_id'), 'mission_needs', ['id'], unique=False)
    op.create_index(op.f('ix_mission_needs_status'), 'mission_needs', ['status'], unique=False)
    op.add_column('missions', sa.Column('mission_need_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_missions_mission_need_id'), 'missions', ['mission_need_id'], unique=False)
    op.create_foreign_key(None, 'missions', 'mission_needs', ['mission_need_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'missions', type_='foreignkey')
    op.drop_index(op.f('ix_missions_mission_need_id'), table_name='missions')
    op.drop_column('missions', 'mission_need_id')
    op.drop_index(op.f('ix_mission_needs_status'), table_name='mission_needs')
    op.drop_index(op.f('ix_mission_needs_id'), table_name='mission_needs')
    op.drop_index(op.f('ix_mission_needs_evidence_gap_dimension'), table_name='mission_needs')
    op.drop_index(op.f('ix_mission_needs_created_at'), table_name='mission_needs')
    op.drop_table('mission_needs')
    # ### end Alembic commands ###
